# Generated by Django 3.1.1 on 2020-09-10 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('bed_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('general', 'general'), ('semi-private', 'semi-private'), ('private', 'private')], max_length=255)),
                ('status', models.CharField(choices=[('empty', 'empty'), ('full', 'full'), ('defective', 'defective')], default='empty', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('assigned_bed', models.ForeignKey(blank=True, db_column='bed_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='covid_hospitals.bed')),
            ],
        ),
    ]
