# Generated by Django 3.1.1 on 2020-09-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='bed_id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
